### ISSUE TITLE
Render in Panel makes Jupyterlab unusable with 8.x upgrade

### ISSUE THREAD

**Issue by singharpit94** [jupyter/jupyter_client#942]
When upgrading from 7.x to 8.x (8.1.0), the render in [panel](https://panel.holoviz.org/) which loads the panel output in an iframe within jupyterlab has stopped working. The greater concern is that once the render in panel is used once post that jupyterlab becomes unusable as such the server is blocked and not able to resolve any further request.

 
![panel-bug](https://user-images.githubusercontent.com/7591673/229688016-c8d2aa09-f386-418d-b3b7-111be96a034c.gif)

Environment:

- Operating System and version: Linux
- JupyterLab version: 3.6
-  jupyter-client: 8.1.0
-  jupyter-core: 5.2.0

Please note jupyter-core needs to be 5.x to make jupyter-client 8.x work in jupyterlab. Also there are no error logs or stack trace to know what and where things are broken.

Can you please check if this is something which can be fixed in jupyter_client or helps us debug more to resolve this issue.

**Comment by ndmlny-qs** [comment]
@singharpit94 what versions of python and panel are you using?

**Comment by ndmlny-qs** [comment]
I've tried to reproduce the error on a local machine using the environments below, but I cannot seem to get it to freeze like you have.

I have a few follow-up questions:

1. Are both Jupyter and Bokeh/Panel running on the same machine?
2. Can you post a gif of the development console? Specifically the `Network` tab and filter only for websockets (like below)?

[websockets.webm](https://user-images.githubusercontent.com/60523020/229914651-cf5eed63-a17b-4aae-b0e2-45c98001c05b.webm)

# environments

## using `conda-forge`

```yaml
name: render-in-panel-conda
channels:
  - conda-forge
dependencies:
  # Development
  - jupyter_client==8.1.0
  - jupyter_core==5.2.0
  - jupyterlab==3.6.0
  - panel==0.14.4
```

## using `pip`

```yaml
name: render-in-panel-pip
channels:
  - conda-forge
dependencies:
  # Development
  - pip
  - pip:
      - jupyter_client==8.1.0
      - jupyter_core==5.2.0
      - jupyterlab==3.6.0
      - panel==0.14.4
```
